--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Homebrew)
-- Dumped by pg_dump version 14.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: janko
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name text NOT NULL,
    color text NOT NULL
);


ALTER TABLE public.categories OWNER TO janko;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: janko
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: janko
--

CREATE TABLE public.expenses (
    id integer NOT NULL,
    category_id integer,
    description text,
    amount double precision NOT NULL,
    date date NOT NULL,
    ignore boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fio_transaction_id integer
);


ALTER TABLE public.expenses OWNER TO janko;

--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: janko
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fio_transactions; Type: TABLE; Schema: public; Owner: janko
--

CREATE TABLE public.fio_transactions (
    id integer NOT NULL,
    external_id text NOT NULL,
    amount double precision NOT NULL,
    date date NOT NULL,
    account text,
    note text,
    message text,
    type text
);


ALTER TABLE public.fio_transactions OWNER TO janko;

--
-- Name: fio_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: janko
--

ALTER TABLE public.fio_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fio_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rules; Type: TABLE; Schema: public; Owner: janko
--

CREATE TABLE public.rules (
    id integer NOT NULL,
    field text NOT NULL,
    operator text NOT NULL,
    value text NOT NULL,
    category_id integer,
    ignore boolean
);


ALTER TABLE public.rules OWNER TO janko;

--
-- Name: rules_id_seq; Type: SEQUENCE; Schema: public; Owner: janko
--

ALTER TABLE public.rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: janko
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


ALTER TABLE public.schema_migrations OWNER TO janko;

--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_fio_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_fio_transaction_id_key UNIQUE (fio_transaction_id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: fio_transactions fio_transactions_external_id_key; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.fio_transactions
    ADD CONSTRAINT fio_transactions_external_id_key UNIQUE (external_id);


--
-- Name: fio_transactions fio_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.fio_transactions
    ADD CONSTRAINT fio_transactions_pkey PRIMARY KEY (id);


--
-- Name: rules rules_pkey; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.rules
    ADD CONSTRAINT rules_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: expenses expenses_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;


--
-- Name: expenses expenses_fio_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_fio_transaction_id_fkey FOREIGN KEY (fio_transaction_id) REFERENCES public.fio_transactions(id) ON DELETE CASCADE;


--
-- Name: rules rules_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: janko
--

ALTER TABLE ONLY public.rules
    ADD CONSTRAINT rules_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--



--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Homebrew)
-- Dumped by pg_dump version 14.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: janko
--

INSERT INTO public.schema_migrations VALUES ('20221001115823_create_categories.rb');
INSERT INTO public.schema_migrations VALUES ('20221001115843_create_expenses.rb');
INSERT INTO public.schema_migrations VALUES ('20221020231423_create_fio_transactions.rb');
INSERT INTO public.schema_migrations VALUES ('20230114181444_nullify_expense_category_id_on_deletion.rb');
INSERT INTO public.schema_migrations VALUES ('20230115121453_create_rules.rb');


--
-- PostgreSQL database dump complete
--

